const quotes = ["I have a great relationship with the blacks.", "Any negative polls are fake news, just like the CNN, ABC, NBC polls in the election. Sorry, people want border security and extreme vetting.", "An ‘extremely credible source’ has called my office and told me that Barack Obama’s birth certificate is a fraud.", "The beauty of me is that I’m very rich.", "I’ve said if Ivanka weren’t my daughter, perhaps I’d be dating her.", "My fingers are long and beautiful, as, it has been well documented, are various other parts of my body.", "You’re disgusting.", "SEE YOU IN COURT, THE SECURITY OF OUR NATION IS AT STAKE!", "My IQ is one of the highest — and you all know it! Please don’t feel so stupid or insecure; it’s not your fault.", "You know, it really doesn’t matter what the media write as long as you’ve got a young, and beautiful, piece of ass.", "The FAKE NEWS media (failing @nytimes, @NBCNews, @ABC, @CBS, @CNN) is not my enemy, it is the enemy of the American People!",
"I will build a great wall – and nobody builds walls better than me, believe me – and I’ll build them very inexpensively. I will build a great, great wall on our southern border, and I will make Mexico pay for that wall. Mark my words.", "All of the women on The Apprentice flirted with me – consciously or unconsciously. That’s to be expected.", "I have never seen a thin person drinking Diet Coke.", "The point is, you can never be too greedy.", "I dealt with Gaddafi. I rented him a piece of land. He paid me more for one night than the land was worth for two years, and then I didn't let him use the land. That's what we should be doing. I don't want to use the word 'screwed,' but I screwed him. That's what we should be doing.", "Stop the EBOLA patients from entering the U.S. Treat them, at the highest level, over there. THE UNITED STATES HAS ENOUGH PROBLEMS!", "I mean, we could say politically correct that look doesn’t matter, but the look obviously matters… like you wouldn’t have your job if you weren’t beautiful.", "Donald J Trump is calling for a total and complete shutdown of Muslims entering the United States, until our country’s representatives can figure out what the hell is going on.", "I would bring back waterboarding and I'd bring back a hell of a lot worse than waterboarding.", "I have no intention of ever running for president.", "I do not wear a rug. My hair is one hundred percent mine.", "A certificate of live birth is not the same thing by any stretch of the imagination as a birth certificate.", "I am the least racist person there is. And I think most people that know me would tell you that. I am the least racist.", "The concept of global warming was created by and for the Chinese in order to make U.S. manufacturing non-competitive.", "This very expensive GLOBAL WARMING bullshit has got to stop. Our planet is freezing, record low temps,and our GW scientists are stuck in ice.", "By the way, I have great respect for China. I have many Chinese friends. They live in my buildings all over the place.", "I think the only difference between me and the other candidates is that I’m more honest and my women are more beautiful.", "In life you have to rely on the past, and that’s called history.", "I will be the greatest jobs president God ever created.", "With the proper woman you don’t need Viagra.", "My life has been about winning. My life has not been about losing."];

function genQuote() {
  const randNum = Math.floor(Math.random() * (quotes.length));
  const quote = quotes[randNum];
  document.getElementById('quote').innerHTML = quote;
  document.title = quote;
  document.getElementById('intro-header').style.background = 'url(https://trumps.lol/' + randNum + '.gif) no-repeat center center';
  document.getElementById('intro-header').style['background-size'] = 'cover';
}

genQuote();
