# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fresh.trumps.lol
title: Fresh Trumps
author: Donald Trump
description: Random Donald Trump gifs for the Masses

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
